create table MJboard(
	BOARD_NUM INT,
	BOARD_NAME VARCHAR(20) NOT NULL,
	BOARD_PASS VARCHAR(15) NOT NULL,
	BOARD_SUBJECT VARCHAR(50) NOT NULL,
	BOARD_CONTENT VARCHAR(2000) NOT NULL,
	BOARD_IMAGE VARCHAR(50) NOT NULL,
	BOARD_READCOUNT INT DEFAULT 0,
	BOARD_DATE DATE,
	PRIMARY KEY(BOARD_NUM)
)DEFAULT CHARSET=utf8;


drop table MJboard;

select * from MJboard;

create table MJreply(
	Reply_NUM INT,
	Reply_WHERE INT,
	Reply_NAME VARCHAR(20) NOT NULL,
	Reply_PASS VARCHAR(15) NOT NULL,
	Reply_CONTENT VARCHAR(2000) NOT NULL,
	PRIMARY KEY(Reply_NUM)
)DEFAULT CHARSET=utf8;

drop table MJreply;